"""
Signal History Schemas
"""

from pydantic import BaseModel, Field
from typing import Optional, List, Literal
from datetime import datetime


class SignalRecord(BaseModel):
    """Record of a signal generated by the system"""
    signal_id: str = Field(description="Unique ID for this signal")
    symbol: str
    timeframe: Literal["swing", "positional"]
    timestamp: datetime
    
    # Signal data
    directional_bias: Literal["bullish", "bearish", "neutral"]
    confidence_score: float = Field(ge=0.0, le=1.0)
    risk_score: int = Field(ge=0, le=100)
    
    # Price at signal time
    entry_price: float
    
    # Scenarios
    base_case_low: float
    base_case_high: float
    base_case_probability: float
    
    bull_case_low: float
    bull_case_high: float
    bull_case_probability: float
    
    bear_case_low: float
    bear_case_high: float
    bear_case_probability: float
    
    invalidation_level: float


class SignalOutcome(BaseModel):
    """Outcome of a signal after specified time period"""
    signal_id: str
    symbol: str
    
    # Timing
    signal_timestamp: datetime
    evaluation_timestamp: datetime
    days_elapsed: int
    
    # Outcome
    entry_price: float
    exit_price: float
    price_change_percent: float
    
    # Evaluation
    direction_correct: bool
    hit_base_case: bool
    hit_bull_case: bool
    hit_bear_case: bool
    hit_invalidation: bool
    
    # Performance
    max_gain_percent: float
    max_loss_percent: float
    
    # Metadata
    outcome_quality: Literal["win", "loss", "breakeven", "invalidated"]


class BacktestStats(BaseModel):
    """Statistics for signal performance"""
    symbol: str
    timeframe: Literal["swing", "positional"]  
    total_signals: int
    
    # Directional accuracy
    bullish_signals: int
    bearish_signals: int
    neutral_signals: int
    direction_accuracy: float = Field(ge=0.0, le=1.0)
    
    # Scenario accuracy
    base_case_hit_rate: float = Field(ge=0.0, le=1.0)
    bull_case_hit_rate: float = Field(ge=0.0, le=1.0)
    bear_case_hit_rate: float = Field(ge=0.0, le=1.0)
    invalidation_rate: float = Field(ge=0.0, le=1.0)
    
    # Performance
    avg_gain_percent: float
    avg_loss_percent: float
    win_rate: float = Field(ge=0.0, le=1.0)
    profit_factor: float
    
    # Time period
    period_start: datetime
    period_end: datetime
